### ISSUE TITLE
It's not quite nice

### ISSUE THREAD

**Issue by icyphox** [NerdyPepper/chestnut.vim#1]
I don't like it. It's nothing compared to `base16-material-palenight`, please fix.
Can you make it look like this?
![image](https://user-images.githubusercontent.com/17672379/44630141-bc964580-a976-11e8-96fa-d6be2845bcdb.png)
Thanks.

**Comment by oppiliappan** [comment]
no

**Comment by icyphox** [comment]
ok

**Comment by oppiliappan** [comment]
ya
